baseURL = "https://jeskaduman.github.io/dpdk-hugo/"
languageCode = "en-us"

title = "DPDK"
theme = "docdock"

publishDir = "docs"

[params]
themeStyle = "flex"
themeVariant = "gray"
showVisitedLinks = true
enableGitInfo = true
disableHomeIcon = true
disableNavChevron = true
disableSearch = true
editURL = "https://github.com/jeskaduman/dpdk-hugo/edit/master/content/"

[outputs]
home = [ "HTML", "RSS", "JSON"]

[[menu.shortcuts]]
name = "<label>Download</label>"
url = "/download"
weight = 1

[[menu.shortcuts]]
name = "<label>Documentation</label>"
identifier = "docs"
url = "/documentation"
weight = 2

[[menu.shortcuts]]
name = "<label>Development Roadmap</label>"
identifier = "devmap"
url = "/DevelopmentRoadmap/"
weight = 3

[[menu.shortcuts]]
name = "<label>Contribute</label>"
identifier = "contribute"
url = "https://www.dpdk.org/contribute"
weight = 4

[[menu.shortcuts]]
name = "<label>DPDK.org</label>"
url = "https://www.dpdk.org"
weight = 5
